# Generated by Django 6.0.5 on 2026-06-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piherz_store', '0002_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo_3d',
            field=models.FileField(blank=True, help_text='Archivo 3D (.glb, .gltf) para visualización interactiva', null=True, upload_to='modelos_3d/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
