# Generated by Django 6.0.5 on 2026-06-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piherz_store', '0004_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='titulo_corto',
            field=models.CharField(blank=True, help_text='Título corto para mostrar en la página de detalle (ej: "Chaqueta para todo tipo de moto")', max_length=200),
        ),
    ]
