# Generated by Django 6.0.5 on 2026-06-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piherz_store', '0006_remove_producto_titulo_corto_producto_titulo_largo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color_predeterminado',
            field=models.CharField(blank=True, help_text='Color seleccionado por defecto', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.CharField(blank=True, help_text='Colores disponibles separados por coma (ej: "Blanco,Beige,Azul,Verde,Negro,Marrón")', max_length=500),
        ),
    ]
