# Generated by Django 6.0.5 on 2026-06-07 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piherz_store', '0007_producto_color_predeterminado_producto_colores'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianteColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Nombre del color (ej: Blanco, Beige, Azul)', max_length=50)),
                ('imagen', models.ImageField(help_text='Imagen del producto en este color', upload_to='productos/colores/')),
                ('orden', models.IntegerField(default=0)),
                ('es_predeterminado', models.BooleanField(default=False, help_text='Marcar como color seleccionado por defecto')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes_color', to='piherz_store.producto')),
            ],
            options={
                'verbose_name': 'Variante de Color',
                'verbose_name_plural': 'Variantes de Color',
                'ordering': ['orden', 'creado'],
            },
        ),
    ]
