# Generated by Django 6.0.5 on 2026-06-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piherz_store', '0008_variantecolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='color_predeterminado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='colores',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modelo_3d',
        ),
        migrations.DeleteModel(
            name='VarianteColor',
        ),
    ]
