# Generated by Django 6.0.5 on 2026-06-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piherz_store', '0009_remove_producto_color_predeterminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='color',
            field=models.CharField(blank=True, help_text='Color de esta variante (ej: Negro, Azul, Gris)', max_length=50),
        ),
    ]
